### ISSUE TITLE
Flow syntax support

### ISSUE THREAD

**Issue by kosanna** [TheSoftwareDesignLab/mutode#14]
That would be great if mutode could correctly skip flow declarations.

Currently if code has flow annotations
eg.
```
const a = (myParam: string): boolean => { /* do something */}
```

mutode is exiting with Unexpected token error
```

Expected behaviour: mutode understands flow notation and does not throw

**Comment by DiegoRBaquero** [comment]
I might add this in the future, for now, I was told by the Stryker team that they support Flow :)

**Comment by simondel** [comment]
Thanks for the mention @DiegoRBaquero, I appreciate it!

@kosanna [Stryker](https://stryker-mutator.io) is another mutation testing framework for the web world. It requires more configuration than Mutode, but it should be able to support your use case. We've had users with Flow in the past that used babel-preset-flow.

Our website contains information on [getting up and running](https://stryker-mutator.io/quickstart.html). For the *transpiler* option, you probably want to go for Babel and for the *mutator* the JavaScript mutator should suit you (as it uses a sub-module of Babel).

If you need any help, feel free to open an issue on our repo or contact us via [gitter](https://gitter.im/stryker-mutator/stryker) or any other way you seem fit 👍 

PS: If you've got Stryker up and running, could you let me know? We're in the middle of writing a comprehensive guide for getting up and running with different types of projects and I think that the configuration of Babel projects and Flow projects is the same in most cases, but I'd like to know for sure :) Current guides can be found [here](https://github.com/stryker-mutator/stryker-handbook) (Babel and Flow guides still have to be made).
