### ISSUE TITLE
Erro Generic

### ISSUE THREAD

**Issue by antoniogeroncio** [TheSoftwareDesignLab/mutode#17]
Please check the tool, I tried exhaustively to generate test with the mutade following the official documentation is not successful, it follows log:

Mutode 153960666 running
Creating a copy of your module... Done

Loading mutators... Done

Verifying and timing your test suite
Deleting copies...Done

Mutode 153960666 finished. Took 30.4s

Test suite most exit with code 0 with no mutants for Mutode to continue

Project: https://github.com/jhipster/generator-jhipster

**Comment by DiegoRBaquero** [comment]
it seems the exit code of running `npm test` is not 0, so it can't continue.
