### ISSUE TITLE
Error executing mutode

### ISSUE THREAD

**Issue by JairoBm13** [TheSoftwareDesignLab/mutode#8]
With Express, which have npm test command, the following error is thrown:

![image](https://user-images.githubusercontent.com/6612456/39065510-a15e283a-4497-11e8-8a98-9bf3041c0515.png)

**Comment by DiegoRBaquero** [comment]
Express had a a file `.name` which wasn't being copied. It should be copied now, fixed by https://github.com/TheSoftwareDesignLab/mutode/commit/8c89b914dffcb2b53fa02262bb3ee9424f1dd806#diff-d964c5d2facc1e1040aabe80430741cbR252

Version 1.1.1 (latest) should work on express.
